[package]
name = "nvmlcontrol"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.95", default-features = false, features = ["std"] }
clap = { version = "4.5.23", default-features = true, features = ["derive"] }
nvml-wrapper = { version = "0.10.0", default-features = false }
pretty-bytes = { version = "0.2.2", default-features = false }
ratatui = "*"
crossterm = "*"
chrono = "*"