[package]
name = "nvmlcontrol"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.95", default-features = false, features = ["std"] }
clap = { version = "4.5.24", default-features = true, features = ["derive"] }
nvml-wrapper = { git = "https://github.com/Quba1/nvml-wrapper.git", default-features = false }
nvml-wrapper-sys = { version = "0.8.0", default-features = true }
pretty-bytes = { version = "0.2.2", default-features = false }
ratatui = { version = "0.29.0", default-features = false, features = ["crossterm"]}
crossterm = { version = "0.28.1", default-features = false }
chrono = { version = "0.4.39", default-features = false, features = ["std", "clock"]}
